### ISSUE TITLE
Feature Requests: Lightness Auto-Balance and RGB Support

### ISSUE THREAD

**Issue by endigo9740** [bobthered/tailwindcss-palette-generator#5]
Hi @bobthered, my name is Chris, I'm from the [Skeleton](https://skeleton.dev/) UI library. I believe you spoke with one of our core contributions Nik recently in this thread:

- https://github.com/bobthered/tailwindcss-palette-generator/issues/3

FYI we're right in the midst of a major update our library's theme generator, of which we use your library pretty heavily.

Here's the old production version:
https://www.skeleton.dev/guides/themes/generator
(enable edit mode, tap Hex mode, then change the colors)

And here's the overhaul on a preview feature branch:
https://skeleton-docs-git-feat-theme-overhauls-skeleton-labs.vercel.app/guides/themes/generator

The swatches for our themes are generated using your palette generator tool, but we've noted there's a bit of balance issue with the colors. Currently lightness is either hardcoded, or can be overwritten manually:
https://github.com/bobthered/tailwindcss-palette-generator/blob/main/src/index.ts#L21

This works fine for generating something fast and approximate, but in our case we're trying to create colors that fulfill two objectives:

1. Swatch 500 should remain 1:1 the hex color passed, to ensure brand consistency (buttons, etc use this shade)
2. Ensure the colors left/right of shade 500 are balanced and aim for an even lightness spread

However we're seeing two issues, which I'll explain in detail below.

## Issue 1: Swatch 500 is not the provided color

Unfortunately in most (read: all?) cases the palette generate does not include the original source color at all.

Here's a quick example:

- We pass `#5c946a`
- We set the following lightness values:

```js
shades: [
	{ name: '50', lightness: 90 },
	{ name: '100', lightness: 85 },
	{ name: '200', lightness: 80 },
	{ name: '300', lightness: 75 },
	{ name: '400', lightness: 65 },
	{ name: '500', lightness: 55 },
	{ name: '600', lightness: 35 },
	{ name: '700', lightness: 30 },
	{ name: '800', lightness: 25 },
	{ name: '900', lightness: 20 }
],
```

- But the resulting colors are:

```
50  - #e0ebe3
100 - #d0e2d4
200 - #c0d8c6
300 - #b1ceb8
400 - #91ba9b
500 - #5c946a // we expected #5c946a here
600 - #456e4f
700 - #3b5e44
800 - #314e38
90 - #273f2d
```

It doesn't matter how we tweak the lightness values, the original color is never present in the output palette. We can manually override the value, but this is doesn't play well with the next issue.

## Issue 2: Color lightness doesn't auto-balance

This is a bit harder to explain/demonstrate, but here's a quick visualization showing what happen if the provided color is on the lighter or darker end of the spectrum:

![Kapture 2022-12-20 at 16 04 14](https://user-images.githubusercontent.com/1509726/208782453-fb849120-6ca4-45c0-991d-ef3d16a424ec.gif)

To point out how we expect this to work, I might refer you to the tint.dev website:
https://www.tints.dev/brand/2522FC

As you pick a new color, that color is set as the mid point (shade 500), which is represented as a square peg on the Distribution chart. Swatches 50-400 and 600-900 are shown as circles. Note how they try to evenly distribute from left to right.

![Screen Shot 2022-12-20 at 4 14 34 PM](https://user-images.githubusercontent.com/1509726/208782569-5148d2db-23fc-423c-bc77-852f66335dbf.png)

![Screen Shot 2022-12-20 at 4 14 39 PM](https://user-images.githubusercontent.com/1509726/208782571-682f416e-4bea-4b99-a860-3a76024069a3.png)

We've realized it's possible to mimic this with your library, but it's going to take a bit of effort to implement. Essentially we would convert the source hex color to HSL (hue saturation lightness) to obtain the base lightness value for our distribution:

![Screen Shot 2022-12-20 at 4 21 54 PM](https://user-images.githubusercontent.com/1509726/208781440-39a58815-abad-4036-8efb-6d6f04ab14a6.png)

So at ~60% lightness, the other shades can be evenly spread with some basic constraints for 50 and 900 to try and avoid pure white/black

![Screen Shot 2022-12-20 at 4 23 53 PM](https://user-images.githubusercontent.com/1509726/208781508-95c891cc-42dc-4d7b-8fce-674c5aa2958d.png)

## Working Together

Mainly I'm reaching out to see if you would have any interest in working on this together, to expand your library to support these extra features. The results will be MUCH more accurate to user's expectations, and it would greatly improve our theme generator.

I'm going to need a solution for this either way, so I certainly don't mind submitting this as a PR. But I may have some questions about how things were implemented if you don't mind. I believe you're on the Skeleton Discord, so happy to discuss on there. My username is @endigo9740 (Chris)

Thanks!

**Comment by endigo9740** [comment]
FYI I forgot to mention the other request - Being able to get not just Hex color results, but also RGB and HSL would be great! Again, happy to coordinate with you on this!

**Comment by endigo9740** [comment]
Quick follow up - I've located this project that seems to work and operate exactly as desired:

- https://javisperez.github.io/tailwindcolorshades/
- https://github.com/javisperez/tailwindcolorshades/blob/master/src/composables/colors.ts

Given we're on a time crunch here I may opt to adapt this for now. But there's some great stuff going on here, including automatic text contrast color generation for overlapping text.

May be worth a look on your end too so I thought I'd share!

**Comment by bobthered** [comment]
Firstly I'm glad you were able to find a solution for these two requests.  The quick answer is, both of these issues were by design but I think [improvements](#proposed-changes) could be made.

## Issue 1: Swatch 500 is not the provided color
The way the palette generator works is it takes the supplied color and converts this to RGB then to HSL.  See your example below:

`#5c946a` -> `rgb(92, 148, 106)` -> `hsl(135, 23%, 47%)`

The shades are then based off the base color's hue and saturation and uses the predetermined, or user supplied, lightness values.  Unfortunately converting between color models isn't an exact match, but if we used `47` for a lightness we would almost retain your supplied color.

```js
tailwindcssPaletteGenerator({
  colors: ['#5c946a'],
  shades: [
    { name: '500', lightness: 47 }
  ]
}),
```
Output
```js
{
  "primary": {
      "500": "#5c936a"
  }
}
```

If you use an online picker tool such as [hslpicker.com/#5c936a](https://hslpicker.com/#5c936a) you'll see the same numbers.

![image](https://user-images.githubusercontent.com/34400277/208927126-84bca693-b7b5-4338-b587-ecfae8a421bc.png)

## Issue 2: Color lightness doesn't auto-balance
Again, the shades are hardcoded, with the ability for the user to override.  The theory is the palette should have a wide range of colors from light to dark.  In the event a user supplies a color that is to one of these extremes, the palette should correct this and provide a full palette of shades.  This isn't taken into consideration in some  other palette generators as evident at the [https://www.tints.dev](https://www.tints.dev) site:

[www.tints.dev/brand/000000](https://www.tints.dev/brand/000000)

![image](https://user-images.githubusercontent.com/34400277/208928900-0e304d4b-b1ed-4916-8317-bc8b7ee58f69.png)

[www.tints.dev/brand/FFFFFF](https://www.tints.dev/brand/FFFFFF)

![image](https://user-images.githubusercontent.com/34400277/208928982-ae3839aa-05bd-48de-90d7-7cf60c7cafa7.png)

## Proposed changes
I think the best change would be for the palette to keep the user supplied color and place it into the palette at a shade value closest to the base color's lightness.  A few examples of this in action would be:

| Input | Input Lightness | Closest Shade | Closest Shade Lightness |
|-------|------------|----------------|-------------------|
|`#5c946a`| `47` | `500` | `46` |
|`#000000`| `0` | `950` | `4` |
|`#ffffff`| `100` | `50` | `98` |
|`#e69cf6`| `79` | `300` | `82` |

If we took this approach, the final palette for these examples would be:

```js
tailwindcssPaletteGenerator({
  colors: ['#5c946a', '#000000', '#ffffff', '#e69cf6'],
  names: ['primary', 'black', 'white', 'secondary'],
}),
```
```diff
{
  "primary": {
      "50": "#f9fbf9",
      "100": "#eff5f1",
      "200": "#e0ebe3",
      "300": "#c7dccc",
      "400": "#8eb899",
-     "500": "#5a9068",
+     "500": "#5c946a",
      "600": "#41684a",
      "700": "#2f4b36",
      "800": "#1b2c20",
      "900": "#0e1610",
      "950": "#080d09"
  },
  "black": {
      "50": "#fafafa",
      "100": "#f2f2f2",
      "200": "#e6e6e6",
      "300": "#d1d1d1",
      "400": "#a3a3a3",
      "500": "#757575",
      "600": "#545454",
      "700": "#3d3d3d",
      "800": "#242424",
      "900": "#121212",
-     "950": "#0a0a0a"
+     "950": "#000000"
  },
  "white": {
-     "50": "#fafafa",
+     "50": "#ffffff",
      "100": "#f2f2f2",
      "200": "#e6e6e6",
      "300": "#d1d1d1",
      "400": "#a3a3a3",
      "500": "#757575",
      "600": "#545454",
      "700": "#3d3d3d",
      "800": "#242424",
      "900": "#121212",
      "950": "#0a0a0a"
  },
  "secondary": {
      "50": "#fdf6fe",
      "100": "#f9e8fd",
      "200": "#f3d0fb",
-     "300": "#e9abf7",
+     "300": "#e69cf6",
      "400": "#d357ef",
      "500": "#b314d7",
      "600": "#800e9a",
      "700": "#5d0a70",
      "800": "#360641",
      "900": "#1b0321",
      "950": "#100213"
  }
}
```

Let me know your thoughts on this approach. 👍

**Comment by endigo9740** [comment]
First off thanks for the great response!

> The shades are then based off the base color's hue and saturation and uses the predetermined, or user supplied, lightness values. Unfortunately converting between color models isn't an exact match, but if we used 47 for a lightness we would almost retain your supplied color.

This is what I suspected. I can understand the challenge faced here as things won't be 1:1. That's what interested my about Javis' library, he actually takes the approach of not ever touching shade 500, he only dynamically creates the shades on the left/right of it:

https://github.com/javisperez/tailwindcolorshades/blob/master/src/composables/colors.ts#L117

It's like two mini palettes that squeeze in on either side.

> Again, the shades are hardcoded, with the ability for the user to override. The theory is the palette should have a wide range of colors from light to dark. In the event a user supplies a color that is to one of these extremes, the palette should correct this and provide a full palette of shades. This isn't taken into consideration in some other palette generators as evident at the https://www.tints.dev/ site:

Yeah I'm aware of the issue with crowding if your color is too far one way or the other. My hope is that by visualizing that to folks or providing a warning, we can discourage folks from building a bad palette. Unfortunately the audience we're targeting may not know much about color, so they may not even realize this is an issue. That's why I'm trying to do as much of the heavy lifting FOR them.

In our case, apps built with our library can supply their own background color. So my hope if someone sets pure white/black for surface color, they'll see things aren't looking quite right and adjust the shades to have variance on top of this. Think of it like depth, we need spacing between each layer rather than everything being flat.

> I think the best change would be for the palette to keep the user supplied color and place it into the palette at a shade value closest to the base color's lightness. A few examples of this in action would be:

I think that's a very creative solution, but unfortunately will not work with our system at present, as we're trying to balance not just a singular theme, but a light/dark mode variation to boot. This adds some obvious challenge. The solution I've developed is to create color pairings:

https://www.skeleton.dev/elements/tokens

![](https://user-images.githubusercontent.com/1509726/195171203-423e5b84-8763-40f1-b3ea-4cb2b8e38108.png)

Essentially shade 500 is treated as the midpoint and this is where we target brand-specific colors to create our preset buttons, accents, etc.

https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/elements/buttons.css#L99

It's not perfect, but the best execution we've found in practice. Really though, if folks fall into a particular edge case, we recommend they custom tailor create their own palette by hand or with various tooling. Essentially the generator will be the "best attempt" but in certain situations it may involve manual intervention. And I think that's fair.

**Comment by bobthered** [comment]
I think we're on the same page with everything, but have different use cases lol.  If the desired result is to have the `500` shade be the supplied brand-specific color, I would use the [https://javisperez.github.io/tailwindcolorshades/](https://javisperez.github.io/tailwindcolorshades/) library.  My goal all along with the palette generator was to provide a full palette regardless of user input or user knowledge of color theory.

I like the idea of pairing the colors.  One thing to note is the palette generator outputs an additional `950` shade.  This might be the best way to accomplish your pairs as well as this would mean the `500` brand-specific color would always be present and not flipped to `400`.

Another interesting note is the choice of the lightness values for each shade.  I think some deeper color theory is needed ( definitely on my part ) to come up with these numbers.  I compiled the `lightness` values from each of tailwind's stock colors, and they are all over the place.  I know the creator's said they hand picked these colors so that makes sense, but I wonder if a different color model could be used to simulate "perceived lightness / darkness."  This would generate a palette closest to tailwind IMHO.

| Color       | 50     | 100    | 200    | 300    | 400    | 500    | 600    | 700    | 800    | 900    |
| ----------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Slate       | 98     | 96     | 91     | 84     | 65     | 47     | 35     | 27     | 17     | 11     |
| Gray        | 98     | 96     | 91     | 84     | 65     | 46     | 34     | 27     | 17     | 11     |
| Zinc        | 98     | 96     | 90     | 84     | 65     | 46     | 34     | 26     | 16     | 10     |
| Neutral     | 98     | 96     | 90     | 83     | 64     | 45     | 32     | 25     | 15     | 9      |
| Stone       | 98     | 96     | 90     | 83     | 64     | 45     | 32     | 25     | 15     | 10     |
| Red         | 97     | 94     | 89     | 82     | 71     | 60     | 51     | 42     | 35     | 31     |
| Orange      | 96     | 92     | 83     | 72     | 61     | 53     | 48     | 40     | 34     | 28     |
| Amber       | 96     | 89     | 77     | 65     | 56     | 50     | 44     | 37     | 31     | 26     |
| Yellow      | 95     | 88     | 77     | 64     | 53     | 47     | 40     | 33     | 29     | 26     |
| Lime        | 95     | 89     | 80     | 67     | 55     | 44     | 35     | 27     | 23     | 20     |
| Green       | 97     | 93     | 85     | 73     | 58     | 45     | 36     | 29     | 24     | 20     |
| Emerald     | 96     | 90     | 80     | 67     | 52     | 39     | 30     | 24     | 20     | 16     |
| Teal        | 97     | 89     | 78     | 64     | 50     | 40     | 32     | 26     | 22     | 19     |
| Cyan        | 96     | 90     | 82     | 69     | 53     | 43     | 36     | 31     | 27     | 24     |
| Sky         | 97     | 94     | 86     | 74     | 60     | 48     | 39     | 32     | 27     | 24     |
| Blue        | 97     | 93     | 87     | 78     | 68     | 60     | 53     | 48     | 40     | 33     |
| Indigo      | 97     | 94     | 89     | 82     | 74     | 67     | 59     | 51     | 41     | 34     |
| Violet      | 98     | 95     | 92     | 85     | 76     | 66     | 58     | 50     | 42     | 35     |
| Purple      | 98     | 95     | 92     | 85     | 75     | 65     | 56     | 47     | 39     | 32     |
| Fuchsia     | 98     | 95     | 91     | 83     | 73     | 61     | 49     | 40     | 33     | 28     |
| Pink        | 97     | 95     | 90     | 82     | 70     | 60     | 51     | 42     | 35     | 30     |
| Rose        | 97     | 95     | 90     | 82     | 71     | 60     | 50     | 41     | 35     | 30     |
| **Average** | **97** | **93** | **86** | **77** | **64** | **52** | **42** | **35** | **28** | **23** |

**Comment by endigo9740** [comment]
Completely understand Bob, thanks for talking through this. And yeah I agree different goals, so no worries.

The idea of using shade 950 as a reserved color is an interesting idea. I'll noodle on that, assuming Tailwind supports it. Their stock colors range 50-900, but should work in theory.

And yeah, the hand picked set is nice because they are just eyeing it, but I'm not sure if there's a programatic way to simulate this without a tremendous effort. But I'll definitely check in if you make progress. At this point I'm just plain curious heh.

Btw, initial test with Javis' script is promising. I've managed to generate a full palette, with each shade needed, and including hex/rgb/on colors (the latter is the determined best value for overlapping text/fill colors)

![Screen Shot 2022-12-21 at 1 20 45 PM](https://user-images.githubusercontent.com/1509726/208986292-9a8adda0-27e3-4e4a-931e-66e72cfb6c5f.png)

Here's the vanilla Tailwind colors in visualized:

![image](https://user-images.githubusercontent.com/1509726/208986553-94d01dc8-f091-424b-8e59-be194386f5f1.png)

Versus the script generated versions passing the hex color per row:

![image](https://user-images.githubusercontent.com/1509726/208986673-df047d37-a375-43cb-b715-e5e88851ce42.png)

The light end is a bit over-tuned, but I'll look to adjust soon.
